spring:
    # DB 연결
    datasource:
    # 설치된 H2 DB와 연결 URL
        url: jdbc:h2:mem:springcoredb
        username: sa
        password:
        # 접속을 위한 드라이버
        driver-class-name: org.h2.Driver
    jpa:
        # JPA? ???? SQL? ? ? ??.
        show-sql: true
        # 객체를 보고 자동으로 테이블 생성 여부. 생성 - create, 비생성 - none
        # 테스트이기 때문에 create로 설정하며
        # 실제로는 none 으로 합니다. create이면 기존의 테이블을 전부 밀어버립니다.
        hibernate:
            ddl-auto: create
        # 콘솔에 sql 예쁘게 찍기
        properties:
            hibernate.format_sql: true
    # 콘솔 확인 을 위한 always
    output:
        ansi:
            enabled: always
    servlet:
        multipart:
            maxFileSize: 10MB
    h2:
        console:
            enabled: true

# ???? ??? ?? trace
logging:
    level:
        org.hibernate.type: trace
